### ISSUE TITLE
Break the reactivity if the collection use ObjectID instead of String

### ISSUE THREAD

**Issue by elainhelen** [aldeed/meteor-delete-button#10]
The delete button works great with 
Benchmarks = new Mongo.Collection('benchmarks', {idGeneration: 'STRING'});

Whenever I click the delete button, the associate data is deleted as expected, and the table will refresh reactively.

But if I have 

Benchmarks = new Mongo.Collection('benchmarks', {idGeneration: 'MONGO'});

Whenever I click the delete button, the data is deleted since I got result 1 from on success hook. But the data won't disappear. and the table will not refresh itself. After I refresh the page manually, the deleted data will disappear.

**Comment by aldeed** [comment]
I can't see how this would be anything related to this package. More likely related to the display code.
