### ISSUE TITLE
Exception in delivering result of invoking '/projects/remove':

### ISSUE THREAD

**Issue by severin-bruhat** [aldeed/meteor-delete-button#6]
Hi, 

I'm using this package to remove objects from my collection "projects".

I have added the button like this :
{{#quickRemoveButton collection="Projects" _id=this._id onError=onError onSuccess=onSuccess beforeRemove=beforeRemove class="btn btn-xs btn-danger"}}
 <span class="glyphicon glyphicon-remove"></span>
{{/quickRemoveButton}}

I have also authorized the remove function : 
if (Meteor.isServer) {
  Projects.allow({
      remove: function (userId, doc) {
      return true;
    }
  });

The project is deleted but it throws this exception : 
Exception in delivering result of invoking '/projects/remove': ["click button"]/<.remove/<@http://meteor-128110.nitrousapp.com:3000/packages/aldeed_delete-button.js?5374a4599af02af385dd7a72d89f3c1f5fe70deb:118:13
Mongo.Collection.prototype[name]/wrappedCallback@http://meteor-128110.nitrousapp.com:3000/packages/mongo.js?3cfe0c5981c197df33036a37574850f057e934a6:621:9
Meteor.bindEnvironment/<@http://meteor-128110.nitrousapp.com:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:983:17
._maybeInvokeCallback@http://meteor-128110.nitrousapp.com:3000/packages/ddp.js?d1840d3ba04c65ffade261f362e26699b7509706:3860:7
.dataVisible@http://meteor-128110.nitrousapp.com:3000/packages

Any idea ?

Thanks for your help

**Comment by aldeed** [comment]
No it does not seem related to this package.

**Comment by severin-bruhat** [comment]
In fact, it tries to call the route myCollection/remove, but this routt doesn't exist, and I think it's not necessary because, it works: the element is deleted. Why is it calling this route ?

**Comment by aldeed** [comment]
That is the default mutation method for removes. It is what is called behind the scenes when you call `collection.remove` in client code. So I don't know where it's erroring, but obviously somewhere after the point where it actually does the removal on the server.
